name: Commit Stage
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-id:
    name: Job name
    runs-on: ubuntu-latest
    steps:
      - name: sub name
        run: echo "Hello World"
